Version 1.1.5: Thu Jan 17 14:03:49 CET 2008
- Recipe for Flac files
- Recipe for Canon CR2 RAW files
- Configure script compatibility fix for Debian-based Linuxes

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -33,7 +33,7 @@ def_CFLAGS="-O3 -Wall"
 MAKE_VARS=
 
 if [ -f config.config ]; then
-    . config.config
+    . ./config.config
 fi
 
 #
@@ -96,7 +96,7 @@ if mv -f config.h config.h.bak 2>/dev/null; then
     trap "mv config.h.bak config.h" 0
 fi
 cat > config.h << EOF
-/* XXX This file automatically generated by configure. */
+/* XXX This file was automatically generated by configure. */
 
 EOF
 
@@ -173,7 +173,11 @@ EOF
     . "$f"
 done
 
-rm -f conftest.c conftest.o conftest
+#
+# Clean up
+#
+trap "" 0
+rm -f config.h.bak conftest.c conftest.o conftest
 
 #
 # Generate Makefile
@@ -200,8 +204,6 @@ if [ -f Makefile.dep ]; then
 fi
 
 chmod 444 Makefile
-
-trap - 0
 
 echo
 echo "Done. Now type 'make' to compile"
