Version 1.0.3: Tue Mar 23 16:02:19 CET 2004
- New recipes for Microsoft Office formats and ELF
- Recipe for gzip now extracts file names, if available
- Proper support was added for resuming an interrupted run
- Output file names now reflect match offsets
- Portability fixes, especially for Cygwin

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9,11 +9,51 @@ env_vars="CC CFLAGS CPPFLAGS LDFLAGS"
 def_CC=cc
 def_CFLAGS="-O3 -Wall"
 
+MAKE_VARS="EXE"
+EXE=
+
+#
+# Helper functions
+#
+
+echo1() { echo $ECHO_N "$1$ECHO_C"; }
+echo2() { echo "$ECHO_T$1"; }
+
+conftest() {
+    $CC $CPPFLAGS $CFLAGS -o conftest $LDFLAGS conftest.c >/dev/null 2>&1 \
+	|| return 1
+    ./conftest
+}
+
+conftest_define() {
+    echo1 "$2"
+    if conftest; then
+	echo "#define $1 1" >> config.h
+	echo2 "yes"
+    else
+	echo2 "no"
+    fi
+}
+
+#
+# Generate config.h
+#
+[ -d config.d ] || {
+    echo "Directory config.d not found. Run configure from the source root."
+    exit 1
+}
+
+rm -f config.h
+cat > config.h << EOF
+/* XXX This file automatically generated by configure. */
+
+EOF
+
 #
 # Environment
 #
 for var in $env_vars; do
-    eval ": \${$var:=\$def_$var}"
+    eval "$var=\${$var:-\$def_$var}"
     export $var
 done
 
@@ -24,15 +64,19 @@ for option; do
     case "$option" in
 
     --help)
-    	cat << EOF
+	cat << EOF
 This will configure $app for your system.
 
 Options:
   --prefix=DIR    Path to install under [$prefix]
   CC=COMMAND      C compiler to use [$CC]
-  CFLAGS=COMMAND  C compiler flags [$CFLAGS]
+  CFLAGS=OPTIONS  C compiler flags [$CFLAGS]
 EOF
 	exit
+	;;
+
+    --strict)
+	export CFLAGS="$CFLAGS -std=c9x -W -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-prototypes -Wredundant-decls"
 	;;
 
     --*=*)
@@ -53,16 +97,22 @@ EOF
 done
 
 #
-# Generate config.h
+# Do tests
 #
-rm -f config.h 2>/dev/null || chmod 644 config.h
-cat > config.h << EOF
-/* XXX This file automatically generated by configure. */
 
-#define COMMAND_PATH "$prefix/share/$app/commands"
-#define RECIPE_PATH  "$prefix/share/$app/recipes"
-EOF
-chmod 444 config.h
+# echo test, stolen from GNU autoconf. This really shows UNIX at its worst...
+case `echo "testing\c"; echo 1,2,3`,`echo -n testing; echo 1,2,3` in
+  *c*,-n*) ECHO_N= ECHO_C='
+' ECHO_T='	' ;;
+  *c*,*  ) ECHO_N=-n ECHO_C= ECHO_T= ;;
+  *)       ECHO_N= ECHO_C='\c' ECHO_T= ;;
+esac
+
+for f in config.d/*; do
+    . "$f"
+done
+
+rm -f conftest.c conftest
 
 #
 # Generate Makefile
@@ -75,7 +125,7 @@ cat > Makefile << EOF
 PREFIX = $prefix
 EOF
 
-for var in $env_vars; do
+for var in $env_vars $MAKE_VARS; do
     eval "val=\"\$$var\""
     echo "$var = $val" >> Makefile
 done
@@ -83,4 +133,5 @@ done
 cat Makefile.in >> Makefile
 chmod 444 Makefile
 
+echo
 echo "Done. Now type 'make' to compile"
